---

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
        auth:
          username: deekayen
          password: $DOCKERHUB_PASSWORD

    environment:
      MOLECULE_DISTRO: debian10

    working_directory: ~/deekayen.molecule_sandbox

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install python test dependencies from requirements.txt.
          command: |
            pip3 install -r requirements.txt

      - run:
          name: Run Molecule Testing CircleCI-locally with Docker.
          command: |
            pipenv run molecule test

workflows:
  version: 2
  on-commit:
    jobs:
      - build
