---

name: Molecule
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'deekayen.molecule_sandbox'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro:
          - debian10
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'deekayen.molecule_sandbox'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python test dependencies from requirements.txt.
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
